### ISSUE TITLE
Allow user to override template TargetDeviceFamily MinVersion (edgeextension)

### ISSUE THREAD

**Issue by thomasguillory** [pwa-builder/PWABuilder-CLI#278]
When generating an edge extension, the manifest set the mininum version required to 10.0.15063.0
This is the most recent version of Windows 10 released in March 2017. However, a lot of extensions are capable to work with a previous version (eg. the anniversary update 10.0.14393.0).

Would it be possible to add an option to override this value ?

**Comment by boyofgreen** [comment]
Hi Thomas, we are playing with the idea of allowing you to define the windows min / max versions in the manifest.  How would you feel about that?

**Comment by thomasguillory** [comment]
It's great. We mainly need to be able to set a windows min version.

Le jeu. 2 nov. 2017 à 21:14, Jeff Burtoft <notifications@github.com> a
écrit :

**Comment by davrous** [comment]
The new Edge based on Chromium is now using a different submission model: https://blogs.windows.com/msedgedev/2019/12/16/get-started-extensions-addons-microsoft-edge-chromium/. We invite you to migrate your previous Edge extension to our new store. Thank you! Closing this issue.
