### ISSUE TITLE
Enable Azure Active Directory authentication

### ISSUE THREAD

**Issue by dtosato** [pwa-builder/PWABuilder-CLI#284]
Hi all,
I am testing ManifoldJS on my SPA hosted by Azure. Allowing anonymous access to the application everything goes fine, but enabling Azure Active Directory (AAD) authentication, the native app produced by ManifoldJS does not work anymore. This because to authenticate a user, AAD redirect to the authentication page (https://login.microsoftonline.com/*) and this is not allowed by the native app. Even adding the authentication page URL to mjs_extended_scope into the app manifest nothing works. So, does anyone know how to enable the Azure authentication on a progressive web app?
Thanks.
Diego

**Comment by boyofgreen** [comment]
Can you do me a favor and give it a try from the preview version of the site.   preview.pwabuilder.com   We are making changes to make SSO "just work".  So... hopefully that "just works".  If that is the case, I can push the changes out to the CLI beta channel as well.  LMK

**Comment by davrous** [comment]
Hello! This issue has been opened for a long time and inactive. Please if you still have this need, please try it on the latest version of our site: www.pwabuilder.com and tell us if something is still wrong with AAD. Thanks!
