### ISSUE TITLE
Can't create an app name with space between words or a non English name

### ISSUE THREAD

**Issue by NoamPaz** [pwa-builder/PWABuilder-CLI#305]
Steps:
1) Set short_name as "My App" in the manifest.json
2) Create an android app. I didn't try IOS, but seems like utils.sanitizeName will replace all spaces for every platform.
3) App name is MyApp instead of My App.
4) If App name is a non English word I get the default value (myPWABuilderApp).

Here is the problematic line in the utils:
sanitizedName = sanitizedName.replace(/[^A-Za-z0-9\.]/g, '');

**Comment by lucaasrojas** [comment]
@NoamPaz I opened a new PR with a fix to this problem. The fix allows to set a short_name with spaces and in Spanish.

**Comment by kbrons** [comment]
Fix already merged, will be live on the next pwabuilder-lib release. In the meantime, you can clone this and the pwabuilder-lib repository locally, [pack](https://docs.npmjs.com/cli/pack.html) and [install](https://docs.npmjs.com/cli/install) the fixed version of the of the lib to your copy of the CLI and generate your app there.
