### ISSUE TITLE
App crashing on startup, receiving *lovely* 1 star reviews

### ISSUE THREAD

**Issue by JudahGabriel** [pwa-builder/PWABuilder-CLI#319]
Some Android users are reporting [my Angular PWA app](https://debuggerdotbreak.judahgabriel.com/2018/04/13/i-built-a-pwa-and-published-it-in-3-app-stores-heres-what-i-learned/) crashing at startup. The Android app was generated from pwabuilder.com.

![image](https://user-images.githubusercontent.com/312936/45380580-aae4ad00-b5c8-11e8-8451-62a69b1916ab.png)
![image](https://user-images.githubusercontent.com/312936/45380590-ae783400-b5c8-11e8-9578-c1f5c9f33d95.png)
![image](https://user-images.githubusercontent.com/312936/45380601-b506ab80-b5c8-11e8-8f1e-ed1643122769.png)
![image](https://user-images.githubusercontent.com/312936/45380617-b8019c00-b5c8-11e8-9b42-4bed74c19208.png)

As you can see from the screenshots, this is happening on a variety of Android devices: 

- Galaxy S7 with Android 8.0 Oreo
- Galaxy S8 with Android 8.0 Oreo
- Nokia 6 with Android 8.1
- Experia XA2 with Android 8.0

However, I cannot reproduce any of these crashes. In my emulator and on a few real Android phones, my app launches fine, including on a Galaxy S7.

Frustratingly, the Google Play Developer Console shows no records of any crashes, nor any "app not responding" (ANRs).

@boyofgreen Any idea what might be going wrong? Or any ideas for debugging this?

**Comment by boyofgreen** [comment]
Hi Judah, I'm sorry I missed this one.  I was looking back through issues and somehow I never addressed this.  I had a similar problem with an android app and it turned out to be a memory issue.  I didn't know exactly what the formula was for crashes, but it seemed to have to do with older devices.
  Our new Android platform should consume much less memory (it is no longer based on cordova), if you want to give that a try, its on preview right now.

**Comment by JudahGabriel** [comment]
Hey no worries, I'm sure you're a busy dude!

I'm interested in giving the new Android platform a try. Is it just preview.pwabuilder.com? (Just loaded it, and it looks so new and shiny, heheh, nice work.)

**Comment by boyofgreen** [comment]
hey @JudahGabriel  just wanted to touch base and see if the new project worked better for you?

**Comment by JudahGabriel** [comment]
I think it's working better. I haven't received reports of crashes now for several weeks. I'll comment back here if I do.

**Comment by JudahGabriel** [comment]
@netcinematics It looks like that's a crash on Windows. My issue is a crash on Android.

Have you tried the [PWA Builder preview](http://preview.pwabuilder.com)?

**Comment by netcinematics** [comment]
Judah, fan of your medium post. It is good. Thank you for blazing that trail. : )
I will double check PREVIEW - thanks for the tip.

**Comment by boyofgreen** [comment]
yes, and just a heads up, we are pulling the design we have on preview and have gone back to the drawing board.  We want to deliver the new design on Feb 8th, with that, we'll move everything in preview out to prod.  When we decided to roll back the design on preview, we got stuck where it was hard to push the updates out to prod wtihout breaking stuff
