### ISSUE TITLE
Big difference between CLI and webversion of PWABuilder?

### ISSUE THREAD

**Issue by ThaDaVos** [pwa-builder/PWABuilder-CLI#342]
Some things we noted:
# Android
1. Old gradle version
2. No TWA - CLI uses Cordova (Old version)
# iOS
1. Old Cordova version
2. Web view error when trying to publish app in the App Store

Is the CLI still being worked on actively? As actively as the Web version?

**Comment by JudahGabriel** [comment]
CLI isn't being worked on regularly. We don't currently have plans to move that forward, our focus is on the PWABuilder site.

**Comment by ThaDaVos** [comment]
Ah that explains a lot, we made an IOS app with the cli (as it's really easy to use, sets up the projects locally etc etc) and got an error from Apple that it was outdated - I also thought the PWABuilder Site used the CLI in the background or something.

Maybe a future idea, split the core of the PWABuilder Website (the non-site part) to it's own package, so it can easily be integrated in a CLI by the community, so both can exist side-by-side and be updated :D

**Comment by JudahGabriel** [comment]
Pinging @davrous to get this on our radar for internal discussion. Closing this issue for now. I'll come back and update this when we have a more solid direction on the CLI.
