### ISSUE TITLE
[Question] cordova-ios specific version

### ISSUE THREAD

**Issue by bigio** [pwa-builder/PWABuilder-CLI#347]
When trying to build my pwa for ios, pwabuilder gives me this error:  
`[debug] pid:11823   : iOS project created with cordova-ios@4.5.5
[debug] pid:11823   : Installing "cordova-plugin-hostedwebapp" for ios
[debug] pid:11823   : Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: <=4.1.9
[debug] pid:11823   : Skipping 'cordova-plugin-hostedwebapp' for ios
[debug] pid:11823   : Installing "cordova-plugin-whitelist" for ios
[debug] pid:11823   : Invalid or unexpected token `
Is it possible to specify a specific version for cordova-ios to let it build ?

**Comment by JudahGabriel** [comment]
Hi, we're no longer supporting iOS at this time; it's why we've removed iOS from pwabuilder.com. See [this thread](https://twitter.com/davrous/status/1242492522213015552) for why we removed iOS support. Basically, Apple has a new store policy that blocks web apps from being approved.

Your best option is to use Cordova manually. Be aware that Apple may not approve your PWA until they change their policy on PWAs in the store.
