### ISSUE TITLE
[Question] How do I set a custom android package name, version code and version name

### ISSUE THREAD

**Issue by teclone** [pwa-builder/PWABuilder-CLI#348]
**Question in detail**
How do I customize platform's package name, version and version code, for instance android platform. Please forgive me if this question has been asked already, I have searched everywhere but found nothing helpful.

**A clear and concise description of what you want to know or confused about.**

Everytime I run a build from the web ui, it always sets the android package name to com.website.twa, version to 1 and version name to 1.0.0.

I would love a way to customize this.

**Describe alternatives you've considered**
My suggestion is, web users can be allowed to upload a twa-manifest.json to their website, where custom configurations for each platform can be put in. for instance, these json would work

```json
[
  {
    "platform": "android",
    "config": {
      "packageName": "package name",
      "version": "android version",
      "vesionName": "android version name",
    }
  }
]
```

**Comment by JudahGabriel** [comment]
@teclone would you mind opening an issue over at [pwabuilder issues](https://)? You're in the wrong repo. 😊

FYI, we've recently added support for changing the package name. That's now live on pwabuilder.com. When you download the Android package, click Options:

![image](https://user-images.githubusercontent.com/312936/81878758-d8bc8a80-953d-11ea-89aa-99a74b2cb2a5.png)

That will let you specify the package name.
