### ISSUE TITLE
mismatch between directory structure generated by generate command and expected by run command for windows10

### ISSUE THREAD

**Issue by MilosRasic** [pwa-builder/PWABuilder-CLI#351]
**Describe the bug**
`generate` command generates windows10/appxmanifest/appxmanifest.xml

`run` command expect windows10/manifest/appxmanifest.xml, so it fails

**To Reproduce**
1. In a temp directory, run `pwabuilder -p windows10 [your favorite test website url]`
2. run `pwabilder run windows10`

**Expected behavior**
Generate and expected directory structure is the same and run command works.

**Screenshots**
![generated](https://user-images.githubusercontent.com/533052/83276209-9303f100-a1d0-11ea-9783-f5fc3e1db6c3.png)
![error](https://user-images.githubusercontent.com/533052/83276225-95fee180-a1d0-11ea-9584-0aa80e31f112.png)

**Desktop (please complete the following information):**
Tested on Linux and Windows 10.

**Additional context**
This was reproduced with a website with no manifest.json so pwabuilder generated one locally. Did not try with a real PWA.

Did some debugging and I believe the problem is in pwabuilder-lib or pwabuilder-windows10. Tried to write my own script that uses pwabuilder-lib directly and there's no trace of CLI code causing the above.

**Comment by JudahGabriel** [comment]
Does it still fail for a website with a manifest?

**Comment by MilosRasic** [comment]
Didn't try. I'm trying to create a package for a self-hosted web app for CE devices which we are porting to Xbox One. Since it's optimized for spatial/directional navigation and 10-foot experience, there's no much sense in providing a manifest.json and turning it into a real PWA for the browser and all the other platforms supported by pwabuilder.

I'll give it a try though and let you know, but I think I've found the root cause. Line 309 in platform.js in pwabuilder-windows10

```
var sourcePath = path.join(platformDir, 'manifest');
```

if I change it to

```
var sourcePath = path.join(platformDir, 'appxmanifest');
```

run command goes through but fails because my Windows 10 is not in dev mode.

**Comment by JudahGabriel** [comment]
@lee-leonardo can you have a look at this?

**Comment by lee-leonardo** [comment]
@MilosRasic has this issue been resolved for you? If not please unclose the issue, but since we haven't heard anything in 2 months I'm considering it closed for now
