### ISSUE TITLE
Can't build Windows 10 package

### ISSUE THREAD

**Issue by gspassky** [pwa-builder/PWABuilder-CLI#355]
PWABuilder CLI isn't working for generating Windows 10. On the website (pwabuilder.com) I can generate some package for Windows, but I can't submit it because App name is wrong. So I want to generate it manually with the CLI. But when I try to make a package for Win10 platform - nothing happens. Looks like this feature is not supported anymore?

I've tried anything... For example, tried to install platform manually:
pwabuilder platform add windows10 https://github.com/pwa-builder/pwabuilder-windows10
- Nothing happens. No errors, but no result

Tried to run 
pwabuilder https://mywebsite.com -d C:\pwa -l info -p windows10
- Generates some folders, but they are empty

When I run simple
pwabuilder https://mywebsite.com
- Many files are created, including Android platform, Cordova... But no Windows10...

**Comment by JudahGabriel** [comment]
From the pwabuilder.com website, when you generate the Windows package, you can click "Download" to download the files, at which time you're free to edit them:

![image](https://user-images.githubusercontent.com/312936/85083952-2c974080-b188-11ea-9685-3b9774016b98.png)

Will that work for you?

Our CLI tools don't get as much love as the website. The Windows 10 packaging is undergoing heavy rewrite to take advantage of Chromium-based Edge, so it's not likely the CLI will see a fix for this.

**Comment by gspassky** [comment]
@JudahGabriel Thanks for your feedback. Of course I've downloaded source files and planned to change icons and rebuild a package for MS Store. But there is no way to rebuild! I don't have Visual Studio (and don't want to buy it - only for one operation). Pwabuilder CLI doesn't work. Is there any other option?

**Comment by gspassky** [comment]
You can run
`pwabuilder https://fillin.app -p windows10`
and you'll see nothing happens. Also nothing happens when I try to build a package from files generated by pwabuilder.com...

**Comment by JudahGabriel** [comment]
Visual Studio Community is free. I'd suggest trying that. 

Because we're reworking the Windows platform to use the new Chromium-based Edge, the CLI issue isn't likely to be fixed.
