### ISSUE TITLE
pwabuilder-cli process not ending. How to use in build process?

### ISSUE THREAD

**Issue by goldingdamien** [pwa-builder/PWABuilder-CLI#359]
With debug logging, pwabuilder-cli is ending with: `[info ] pwabuilder  : The application(s) are ready.`.
The process does not seem to end. Tried in Windows 10 bash and powershell.
If I want to await the end of this command what should I do?

**Comment by JudahGabriel** [comment]
As it stands today, the CLI is deprecated. We may in the future rennovate and get things working, but today, we're focused on providing the best experience via pwabuilder.com.
