### ISSUE TITLE
Support for provisioning package ppkg based installation for Windows based PWA

### ISSUE THREAD

**Issue by techyrajeev** [pwa-builder/PWABuilder-CLI#361]
is there any way I can create ppkg out of generated appx/msix bundle so that it can be distributed without windows store?
How can I sign the package with self certificate or any other certificate?

**Comment by JudahGabriel** [comment]
Hi,

That is outside the supported scope of PWABuilder.

What I recommend you do generate your package here: https://pwabuilder-win-chromium-platform.centralus.cloudapp.azure.com/

And make sure the arguments include "allowSigning: true". 

Then, you should be able to sign your app using the steps here: https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool
