### ISSUE TITLE
Can we bring this to Fastlane so we can easily package our apps and submit to the store [New Idea] 

### ISSUE THREAD

**Issue by antonioberetini** [pwa-builder/PWABuilder-CLI#364]
We use FastLane to automate our hybrid app deployment on iOS and Android using https://fastlane.tools/ which makes the whole process streamlined and easy. It would be great if someone would create a plugin for https://fastlane.tools/ To accelerate adoption of PWA on Windows Stores. Our app is a PWA with a native layer wrapped with Capacitor.js which allows us to deploy the same app on the web, iOS and Android. I would kill to be able to do the same with Window's Store.

Hybrid framework's like Ionic are all using Fastlane as their automation protocol to help businesses to deploy their apps quicker, this is something that Windows should invest time into as well.

**Comment by JudahGabriel** [comment]
Thanks for the suggestion. Our main repo is https://github.com/pwa-builder/PWABuilder - can you post this in that repo? It will get more TLC.
